# Generated by Django 5.2.10 on 2026-01-26 23:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se abrió la sesión', verbose_name='Fecha de Apertura')),
                ('closing_timestamp', models.DateTimeField(blank=True, help_text='Fecha y hora en que se cerró la sesión', null=True, verbose_name='Fecha de Cierre')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efectivo inicial en caja al abrir el turno', max_digits=10, verbose_name='Balance de Apertura')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo final en caja al cerrar el turno', max_digits=10, null=True, verbose_name='Balance de Cierre')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-opening_timestamp'],
            },
        ),
    ]
