# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='user',
            field=models.ForeignKey(help_text='Usuario responsable de esta sesión de caja', on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['user', 'status'], name='cash_sessio_user_id_3a3d86_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['status'], name='cash_sessio_status_10e88b_idx'),
        ),
    ]
