# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT', 'Tarjeta de Débito'), ('CREDIT', 'Tarjeta de Crédito'), ('TRANSFER', 'Transferencia')], max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago sin incluir intereses', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Base')),
                ('card_type', models.CharField(blank=True, choices=[('VISA', 'VISA'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('CABAL', 'Cabal'), ('NARANJA', 'Naranja'), ('MAESTRO', 'Maestro'), ('OTHER', 'Otra')], help_text='Requerido para pagos con tarjeta', max_length=20, null=True, verbose_name='Tipo de Tarjeta')),
                ('installments', models.PositiveIntegerField(default=1, help_text='Número de cuotas para tarjetas de crédito', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Cuotas')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa de interés mensual aplicada', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Interés (%)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total incluyendo intereses', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
