# Generated by Django 5.2.10 on 2026-01-26 02:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_type',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('CABAL', 'Cabal'), ('NARANJA', 'Naranja'), ('MAESTRO', 'Maestro'), ('OTHER', 'Otra')], help_text='Requerido para pagos con tarjeta', max_length=20, null=True, verbose_name='Tipo de Tarjeta'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.PositiveIntegerField(default=1, help_text='Número de cuotas para tarjetas de crédito', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Cuotas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa de interés mensual aplicada', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Interés (%)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total incluyendo intereses', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto del pago sin incluir intereses', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Base'),
        ),
    ]
