# Generated by Django 5.2.10 on 2026-01-26 02:55

from django.db import migrations


def populate_total_amount(apps, schema_editor):
    """
    Migración de datos: establece total_amount = amount para registros existentes.

    Para transacciones existentes que no tienen intereses calculados,
    el total es igual al monto base.
    """
    Transaction = apps.get_model('payments', 'Transaction')

    # Actualizar todas las transacciones existentes
    # Usar F() expression para copiar el valor de amount a total_amount
    from django.db.models import F
    Transaction.objects.filter(total_amount=0).update(total_amount=F('amount'))


def reverse_populate(apps, schema_editor):
    """
    Reversión: no es necesario hacer nada, los datos se mantienen.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_card_type_transaction_installments_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_total_amount, reverse_populate),
    ]
