# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Nombre desnormalizado para historial', max_length=200, verbose_name='Producto')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('vat_rate', models.CharField(default='21.00', help_text='Desnormalizado para historial fiscal', max_length=5, verbose_name='Tasa de IVA')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento Global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_session', models.ForeignKey(help_text='Sesión de caja a la que pertenece esta venta', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cash_session.cashsession', verbose_name='Sesión de Caja')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
