# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Referencia al producto (se mantiene desnormalización)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_line_items', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='salelineitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sale.sale'),
        ),
    ]
