# Generated by Django 6.0.1 on 2026-01-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelineitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Referencia al producto (se mantiene desnormalización)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_line_items', to='products.product', verbose_name='Producto'),
        ),
    ]
