# Generated by Django 5.2.10 on 2026-01-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sale_id_alter_salelineitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelineitem',
            name='vat_rate',
            field=models.CharField(default='21.00', help_text='Desnormalizado para historial fiscal', max_length=5, verbose_name='Tasa de IVA'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salelineitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
