# Generated by Django 5.2.10 on 2026-01-25 03:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0003_alter_sale_id_alter_salelineitem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Autorización'), ('AUTHORIZED', 'Autorizada (CAE obtenido)'), ('REJECTED', 'Rechazada por AFIP')], default='DRAFT', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_tax_id', models.CharField(blank=True, max_length=20)),
                ('customer_tax_category', models.CharField(max_length=2)),
                ('net_untaxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_taxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cae', models.CharField(blank=True, max_length=14)),
                ('cae_expiration', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Errores AFIP u observaciones')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sale.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VATAliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_aliquots', to='invoices.invoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['cae'], name='invoices_in_cae_bc99a8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sale'], name='invoices_in_sale_id_77e694_idx'),
        ),
    ]
