# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente de Autorización'), ('AUTHORIZED', 'Autorizada (CAE obtenido)'), ('REJECTED', 'Rechazada por AFIP')], default='DRAFT', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_tax_id', models.CharField(blank=True, max_length=20)),
                ('customer_tax_category', models.CharField(max_length=2)),
                ('net_untaxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_taxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cae', models.CharField(blank=True, max_length=14)),
                ('cae_expiration', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Errores AFIP u observaciones')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VATAliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
