# Generated by Django 5.2.10 on 2026-01-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI/CUIT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('tax_category', models.CharField(choices=[('CF', 'Consumidor Final'), ('EX', 'Exento'), ('RI', 'Responsable Inscripto'), ('MT', 'Monotributo')], default='CF', max_length=2, verbose_name='Categoría Tributaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name'], name='customers_c_last_na_5ff5d1_idx'), models.Index(fields=['tax_id'], name='customers_c_tax_id_c2c068_idx')],
            },
        ),
    ]
