# Generated by Django 6.0.1 on 2026-01-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='locality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_category',
            field=models.CharField(choices=[('CF', 'Consumidor Final'), ('EX', 'Exento'), ('RI', 'Responsable Inscripto'), ('MT', 'Monotributo')], default='CF', max_length=2, verbose_name='Categoría Tributaria'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI/CUIT'),
        ),
    ]
