# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('SALE', 'Venta'), ('PURCHASE', 'Compra'), ('ADJ_IN', 'Ajuste Entrada'), ('ADJ_OUT', 'Ajuste Salida'), ('TRANS_IN', 'Transferencia Entrada'), ('TRANS_OUT', 'Transferencia Salida'), ('RETURN', 'Devolución')], max_length=20, verbose_name='Tipo')),
                ('delta_qty', models.DecimalField(decimal_places=3, help_text='Positivo para entradas, negativo para salidas', max_digits=10, verbose_name='Cambio de Cantidad')),
                ('previous_qty', models.DecimalField(decimal_places=3, help_text='Stock antes del movimiento (para auditoría)', max_digits=10, verbose_name='Cantidad Anterior')),
                ('reference', models.CharField(blank=True, help_text='ID de venta, orden de compra, etc.', max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Cantidad Actual')),
                ('min_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Punto de reorden', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Cantidad Mínima')),
                ('max_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Capacidad máxima de almacenamiento', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Cantidad Máxima')),
                ('location', models.CharField(default='PRINCIPAL', help_text='Ubicación física del stock (ej: PRINCIPAL, DEPOSITO)', max_length=100, verbose_name='Ubicación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['product__name'],
            },
        ),
    ]
