# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='movement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stock', verbose_name='Stock'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'location'], name='inventory_s_product_4a6ef8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'location')},
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['stock', '-created_at'], name='inventory_m_stock_i_32c196_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['movement_type'], name='inventory_m_movemen_6d66c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['reference'], name='inventory_m_referen_7ace6c_idx'),
        ),
    ]
