# Generated by Django 5.2.10 on 2026-01-26 23:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta unitario (máx: 9.999.999.999.999,99)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Venta')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisición (opcional, máx: 9.999.999.999.999,99)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo')),
                ('vat_rate', models.CharField(choices=[('21.00', 'IVA 21%'), ('10.50', 'IVA 10.5%'), ('27.00', 'IVA 27%'), ('5.00', 'IVA 5%'), ('2.50', 'IVA 2.5%'), ('0.00', 'IVA 0% (Exento)')], default='21.00', help_text='Alícuota de IVA aplicable al producto', max_length=5, verbose_name='Tasa de IVA')),
                ('is_active', models.BooleanField(default=True, help_text='Solo productos activos pueden venderse', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx')],
            },
        ),
    ]
