# Generated by Django 5.2.10 on 2026-01-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.CharField(choices=[('21.00', 'IVA 21%'), ('10.50', 'IVA 10.5%'), ('27.00', 'IVA 27%'), ('5.00', 'IVA 5%'), ('2.50', 'IVA 2.5%'), ('0.00', 'IVA 0% (Exento)')], default='21.00', help_text='Alícuota de IVA aplicable al producto', max_length=5, verbose_name='Tasa de IVA'),
        ),
    ]
