# Generated by Django 5.2.10 on 2026-01-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electrónica'), ('FOOD', 'Alimentos'), ('BEVERAGES', 'Bebidas'), ('CLOTHING', 'Indumentaria'), ('HARDWARE', 'Ferretería'), ('STATIONERY', 'Librería'), ('HEALTH', 'Salud'), ('OTHER', 'Otros')], default='OTHER', help_text='Categoría del producto para clasificación', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
    ]
