# Generated by Django 5.2.10 on 2026-01-27 23:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Anterior')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Nuevo')),
                ('change_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de cambio (positivo = aumento, negativo = disminución)', max_digits=8, verbose_name='Porcentaje de Cambio')),
                ('reason', models.CharField(choices=[('BULK_UPDATE', 'Actualización masiva'), ('MANUAL_EDIT', 'Edición manual'), ('INITIAL_PRICE', 'Precio inicial'), ('CORRECTION', 'Corrección'), ('PROMOTION', 'Promoción'), ('COST_ADJUSTMENT', 'Ajuste por costos')], default='MANUAL_EDIT', max_length=20, verbose_name='Razón del Cambio')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre el cambio', verbose_name='Notas')),
                ('bulk_operation_id', models.CharField(blank=True, db_index=True, help_text='ID para agrupar cambios de una misma operación masiva', max_length=50, verbose_name='ID de Operación Masiva')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['product', '-changed_at'], name='products_pr_product_f0e7be_idx'), models.Index(fields=['-changed_at'], name='products_pr_changed_a0647a_idx'), models.Index(fields=['bulk_operation_id'], name='products_pr_bulk_op_d538c1_idx'), models.Index(fields=['changed_by'], name='products_pr_changed_ccc179_idx')],
            },
        ),
    ]
